### ISSUE TITLE
Bug: missing parameter in deploy

### ISSUE THREAD

**Issue by ccMatrix** [dei79/node-azure-deploy#4]
There is an error in the current version in respect to excludes parameter that was also added. I noted the line in the commit. Can you have a look?

**Comment by dei79** [comment]
What error do you mean? Can you describe what the current behaviour is and what the expected behaviour is? Thanks

**Comment by ccMatrix** [comment]
The website deployment uses the git deployment manager in the background. It forwards the sources folder and commit message to the git deployment manager in the deploy method. However git deployment manager expects an "excludes" parameter which is not provided.

This creates an error in the deploy method. See website deployment manager in line 25. There the parameter is missing.

Instead of:
return gitDeploymentManager.deploy(sourceDir, commitMessage);

It should be:
return gitDeploymentManager.deploy(sourceDir, [], commitMessage);

**Comment by dei79** [comment]
Fixed with 0.5.4
